---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    component: {{ .Values.name }}
    tier: {{ .Values.tier }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 70%
      maxSurge: 25%
  selector:
    matchLabels:
      app: {{ .Values.app }}
      component:  {{ .Values.name }}
      tier: {{ .Values.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        component:  {{ .Values.name }}
        tier: {{ .Values.tier }}
    spec:
      containers:
      - name: {{ .Values.app }}
        image: {{ .Values.deployment.image.name }}
        imagePullPolicy:  {{ .Values.deployment.image.pullPolicy }}
        {{- if .Values.environment }}
        env:
        {{- range $name, $value := .Values.environment }}
	  - {{ $name }}
            {{ $value }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort:  {{ .Values.deployment.ports.port }}
          protocol:  {{ .Values.deployment.ports.protocol }}
          name: {{ .Values.deployment.ports.name }}

        {{- if .Values.deployment.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.deployment.livenessProbe.path }}
            port:  {{ .Values.deployment.ports.port }}
          initialDelaySeconds:  {{ .Values.deployment.livenessProbe.initialDelaySeconds }}
          timeoutSeconds:  {{ .Values.deployment.livenessProbe.timeoutSeconds }}
        {{- end }}

        {{- if .Values.deployment.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.deployment.readinessProbe.path }}
            port: {{ .Values.deployment.ports.port }}
          initialDelaySeconds: {{ .Values.deployment.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.deployment.readinessProbe.timeoutSeconds }}
        {{- end }}
      imagePullSecrets:
      - name: {{ .Values.deployment.image.dockerRegistry }}
