{{- if .Values.service.enabled -}}
---
kind: Service
apiVersion: v1
metadata:
  name:  {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ .Values.app }}
    component:  {{ .Values.name }}
    tier:  {{ .Values.tier }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.ports.port }}
  selector:
    app: {{ .Values.app }}
    component:  {{ .Values.name }}
    tier:  {{ .Values.tier }}
{{- end -}}